apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: was
type: Opaque
stringData:
  url: "jdbc:mysql://mysql-dr-blue.mysql.database.azure.com:3306/pocketbank?useSSL=true&requireSSL=false&serverTimezone=UTC"
  username: "mysqladmin"
  password: "SecureP@ssw0rd123!"
