# GitOps Repository Structure
# pocketbank-gitops/
#
# ├── base/
# │   ├── kustomization.yaml
# │   ├── namespace.yaml
# │   ├── deployment.yaml
# │   ├── service.yaml
# │   ├── ingress.yaml
# │   ├── configmap.yaml
# │   ├── secret.yaml (sealed-secrets 사용)
# │   └── hpa.yaml
# │
# ├── overlays/
# │   ├── aws-dev/
# │   │   ├── kustomization.yaml
# │   │   └── patches/
# │   ├── aws-staging/
# │   │   ├── kustomization.yaml
# │   │   └── patches/
# │   ├── aws-prod/
# │   │   ├── kustomization.yaml
# │   │   └── patches/
# │   ├── azure-dev/
# │   │   ├── kustomization.yaml
# │   │   └── patches/
# │   └── azure-prod/
# │       ├── kustomization.yaml
# │       └── patches/
# │
# └── charts/
#     └── pocketbank/
#         ├── Chart.yaml
#         ├── values.yaml
#         └── templates/

---
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: pocketbank-base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  app: pocketbank
  managed-by: argocd

---
# base/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: pocketbank
  labels:
    app: pocketbank

---
# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketbank
  namespace: pocketbank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pocketbank
  template:
    metadata:
      labels:
        app: pocketbank
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: pocketbank
      containers:
        - name: pocketbank
          image: pocketbank:latest  # kustomize로 오버라이드
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: pocketbank-config
                  key: spring.profiles.active
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: pocketbank-db-secret
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pocketbank-db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pocketbank-db-secret
                  key: password
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: pocketbank
                topologyKey: kubernetes.io/hostname

---
# base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pocketbank
  namespace: pocketbank
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: pocketbank

---
# base/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pocketbank
  namespace: pocketbank
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pocketbank
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
# overlays/aws-prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pocketbank

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

commonLabels:
  environment: production
  cloud: aws

images:
  - name: pocketbank
    newName: ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/pocketbank
    newTag: latest

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/ingress-patch.yaml

configMapGenerator:
  - name: pocketbank-config
    behavior: merge
    literals:
      - spring.profiles.active=prod,mysql

secretGenerator:
  - name: pocketbank-db-secret
    type: Opaque
    literals:
      - url=jdbc:mysql://pocketbank-db.cluster-xxx.ap-northeast-2.rds.amazonaws.com:3306/pocketbank
    # username, password는 sealed-secrets로 관리

replicas:
  - name: pocketbank
    count: 3

---
# overlays/aws-prod/patches/deployment-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketbank
spec:
  template:
    spec:
      nodeSelector:
        tier: was
      tolerations:
        - key: "tier"
          operator: "Equal"
          value: "was"
          effect: "NoSchedule"
      containers:
        - name: pocketbank
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi

---
# overlays/aws-prod/patches/ingress-patch.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocketbank
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:ACCOUNT_ID:certificate/CERT_ID
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  rules:
    - host: pocketbank.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pocketbank
                port:
                  number: 80
