# others/cicd/canary/flagger-setup.yaml
# Flagger를 사용한 Canary 배포 설정

# =================================================
# Flagger 설치 가이드
# =================================================
# kubectl apply -f https://raw.githubusercontent.com/fluxcd/flagger/main/artifacts/flagger/crd.yaml
# kubectl apply -k github.com/fluxcd/flagger//kustomize/kubernetes

---
# =================================================
# Flagger Namespace
# =================================================
apiVersion: v1
kind: Namespace
metadata:
  name: flagger-system

---
# =================================================
# WAS Canary Deployment 설정
# =================================================
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: petclinic-was
  namespace: was
spec:
  # 타겟 Deployment
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-was
  
  # 프로그레시브 배포 전략
  progressDeadlineSeconds: 600
  
  # HPA 참조 (Auto Scaling)
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: petclinic-was
  
  # Service 설정
  service:
    port: 8080
    targetPort: 8080
    portDiscovery: true
  
  # Canary 분석 설정
  analysis:
    # 분석 주기
    interval: 1m
    
    # 분석 반복 횟수 (10분 동안)
    iterations: 10
    
    # 임계값 (이 횟수만큼 실패하면 롤백)
    threshold: 5
    
    # 최대 가중치 (최종 단계)
    maxWeight: 50
    
    # 가중치 증가 단계
    stepWeight: 10
    
    # 메트릭 기준
    metrics:
      # 요청 성공률 (99% 이상)
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      
      # 요청 지속 시간 (500ms 이하)
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 1m
    
    # Webhook 테스트 (선택사항)
    webhooks:
      # 배포 전 테스트
      - name: pre-rollout
        type: pre-rollout
        url: http://flagger-loadtester.flagger-system/
        timeout: 15s
        metadata:
          type: bash
          cmd: "curl -sd 'test' http://petclinic-was-canary.was:8080/actuator/health | grep UP"
      
      # 부하 테스트
      - name: load-test
        url: http://flagger-loadtester.flagger-system/
        timeout: 5s
        metadata:
          type: cmd
          cmd: "hey -z 1m -q 10 -c 2 http://petclinic-was-canary.was:8080/actuator/health"

---
# =================================================
# Web Canary Deployment 설정
# =================================================
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: petclinic-web
  namespace: web
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-web
  
  progressDeadlineSeconds: 600
  
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: petclinic-web
  
  service:
    port: 80
    targetPort: 80
    portDiscovery: true
  
  analysis:
    interval: 1m
    iterations: 10
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      
      - name: request-duration
        thresholdRange:
          max: 200  # Nginx는 더 빨라야 함
        interval: 1m
    
    webhooks:
      - name: pre-rollout
        type: pre-rollout
        url: http://flagger-loadtester.flagger-system/
        timeout: 15s
        metadata:
          type: bash
          cmd: "curl -s http://petclinic-web-canary.web | grep 'Spring PetClinic'"
      
      - name: load-test
        url: http://flagger-loadtester.flagger-system/
        timeout: 5s
        metadata:
          type: cmd
          cmd: "hey -z 1m -q 10 -c 2 http://petclinic-web-canary.web/"

---
# =================================================
# Alert Provider (Slack 알림)
# =================================================
apiVersion: flagger.app/v1beta1
kind: AlertProvider
metadata:
  name: slack
  namespace: flagger-system
spec:
  type: slack
  channel: deployments
  username: flagger
  # Slack Webhook URL (Secret으로 관리)
  secretRef:
    name: slack-webhook
    key: url

---
# =================================================
# Slack Webhook Secret
# =================================================
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  namespace: flagger-system
type: Opaque
stringData:
  url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"

---
# =================================================
# Flagger Load Tester (부하 테스트용)
# =================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger-loadtester
  namespace: flagger-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagger-loadtester
  template:
    metadata:
      labels:
        app: flagger-loadtester
    spec:
      containers:
      - name: loadtester
        image: ghcr.io/fluxcd/flagger-loadtester:0.31.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        command:
        - ./loadtester
        - -port=8080
        - -log-level=info
        - -timeout=1h
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: flagger-loadtester
  namespace: flagger-system
spec:
  type: ClusterIP
  selector:
    app: flagger-loadtester
  ports:
  - name: http
    port: 80
    targetPort: http

---
# =================================================
# HPA for WAS (Canary와 연동)
# =================================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-was
  namespace: was
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-was
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max

---
# =================================================
# HPA for Web (Canary와 연동)
# =================================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-web
  namespace: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-web
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 0
